# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "03:00"
      timezone: Europe/Berlin
    assignees:
      - "sblauth"
    groups:
      core-workflow:
        patterns:
          - "actions/*"
      conda:
        patterns:
          - "conda-incubator/*"
      docker:
        patterns:
          - "docker/*"
      security-scanning:
        patterns:
          - "github/codeql-action"
          - "github/ossar-action"
          - "ossf/*"
      coverage:
        patterns:
          - "py-cov-action/*"
      releases:
        patterns:
          - "nowsprinting/*"
          - "softprops/*"
          - "pypa/*"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "03:00"
      timezone: Europe/Berlin
    allow:
      - dependency-type: "all"
    assignees:
      - "sblauth"
