version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.11"

sphinx:
  configuration: docs/source/conf.py
  builder: dirhtml
  fail_on_warning: true

formats:
  - pdf

python:
  install:
  - requirements: docs/requirements.txt
