name: mpi_tests

on:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: '17 22 * * *'

env:
  OMP_NUM_THREADS: 1
  
jobs:
  tests:
    name: MPI (py=${{ matrix.python-version }}, n=${{ matrix.no-cores}} , ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        no-cores: [1, 2, 3]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install micromamba
      uses: mamba-org/provision-with-micromamba@main
      with:
        environment-file: .github/micromamba/testenv.yml
        extra-specs: |
          fenics=2019
          meshio">=5.0.0"
          pytest">=7.0.0"
          deprecated">=1.2.12"
          gmsh">=4.8"
          mpich
          python=${{ matrix.python-version }}

    - name: Install package
      run: |
        pip install .

    - name: Run tests
      run: |
        mpirun -n ${{ matrix.no-cores }} python3 -m pytest tests/
